### ISSUE TITLE
Should not bake in OkHttp and Retrofit

### ISSUE THREAD

**Issue by markstubhub** [vimeo/vimeo-networking-java#100] opened 2016-06-21 22:37 UTC
#### Issue Summary
Applications cannot use other versions of OkHttp and Retrofit than those bundled in this library

#### Reproduction Steps
Many use cases. Modify this project https://github.com/fs-opensource/android-tutorials-picasso to include your library. Then try to get  the demo loadImageViaUnsafeOkHttpPicassoInstance(); to work. 

#### Expected Behavior
Should work

#### Actual Behavior
Various forms of linkage errors. Abstract methods being called.

**Comment by kevinzetterstrom** [comment] 2016-06-22 14:01
How are you including this repo, via submodule (```compile project(':vimeo-networking-java:vimeo-networking'```) or jcenter (```compile 'com.vimeo.networking:vimeo-networking:1.0.1'```)?

Gradle will normally pick the latest version of any included dependency unless you force a choice of your own. For instance, if you include vimeo-networking-java via submodule, it picks up the default branch, v1.1.0. This branch includes OKHttp 3.2.0, which is the same version in the app build.gradle of the PicassoTutorial, so nothing should seem strange there. However, if I changed the build.gradle of the PicassoTutorial to say ```compile 'com.squareup.okhttp3:okhttp:3.1.0'```, then running ```gradlew app:dependencies``` will show it picks up 3.2.0. If this is not what you want, you can force 3.1.0 to be used with the following:
```compile ('com.squareup.okhttp3:okhttp:3.1.0') {
        force = true
    }```
I just did that, and the Picasso demo runs fine, I see all 4 images in the "Picasso.Builder Basics" activity.

I also tried including vimeo-networking-java using JCenter, in this case running  ```gradlew app:dependencies``` forces  3.2.0 of OkHttp on our library, since the version of this library on JCenter is currently on OKHttp 3.0.0-RC1. Running the Picasso Tutorial again, I see all 4 images in the "Picasso.Builder Basics" activity.

For reference, I added the vimeo-networking statement as the last dependency in the Picasso gradle file, under butterknife.

If you are still having issues, can you be a little more specific, with detailed steps for us to reproduce? We'd love to help you get our library integrated into whatever project you are working on!

**Comment by kevinzetterstrom** [comment] 2016-06-24 15:33
@markstubhub are you still having issues? Please reply either way.

**Comment by kevinzetterstrom** [comment] 2016-07-12 14:00
Closing this issue. @markstubhub if you feel that it should be reopened lettuce know!

**Closed by kevinzetterstrom** 2016-07-12 14:00 UTC
