### ISSUE TITLE
Library is not syncing in android studio

### ISSUE THREAD

**Issue by divyashamar** [vimeo/vimeo-networking-java#351] opened 2018-11-15 12:01 UTC
I have tried to use this Library as a gradle dependency.. but its showing above issue.

But I have tried using 1.1.2 its sync successfully. I am trying to run the example project.. 
 I need help..

Thanks
DIVYA PRAKASH

**Comment by AkshayGangurde** [comment] 2018-11-21 10:44
I'm facing the same issue with 1.1.3

**Comment by msya** [comment] 2018-11-30 15:34
Version 1.1.3 hasn't been release yet. We are working on the releasing it soon. Version 1.1.2 is the latest version of the library.

**Comment by msya** [comment] 2018-12-04 14:07
Closing this issue, because it is a duplicate of #324.

**Closed by msya** 2018-12-04 14:07 UTC
