### ISSUE TITLE
Progress Bar is not displayed in the webview

### ISSUE THREAD

**Issue by burhanshakir** [vimeo/vimeo-networking-java#212] opened 2017-05-23 13:12 UTC
#### Issue Summary
When loading video in the webview, i am able to see the progress/seek bar for the first time, but after the progress/seek bar is hidden,onclicking of the webview it isn't displayed again

#### Reproduction Steps
Load video in the Webview and click on the screen

#### Expected Behavior
The progress/seek bar to be displayed/hidden

#### Actual Behavior
Nothing

**Comment by kevinzetterstrom** [comment] 2017-06-23 17:12
@burhanshakir I wanted to just touch base on this so you know it wasn't being swept under the rug.

I reproduced your issue fairly easily. If I extract the actual video url from within that `embed.html` iframe, then no issues occur.

We have issued a formal request to our API team to send us a new field that does not contain the iframe code, but just the video url. When that is made ready, we will do our best to integrate it into this library as quickly as possible and then I will respond here to let you know it is ready. This should solve the issue for you.

**Comment by kevinzetterstrom** [comment] 2017-07-31 21:02
@burhanshakir this topic has been a big conversation over the past two months between my team, our API team, and our player team. Our player team owns the embed iframe code, since it's our embedded player that is shown as a result of this. The API team proxies the embed code to us on their behalf so that it can be consumed using this library. What this comes down to is that in order for this to work, our player team would need to offer full support for Android WebViews. Unfortunately, the player team has come to the conclusion that they will not offer official support for Android WebViews. 

With a heavy heart I will be closing this issue since it is something we are choosing to not officially support. I will be updating the readme to reflect this decision.

**Closed** 2017-07-31 21:08 UTC
